[phases.setup]
nixPkgs = ["nodejs-20_x", "chromium", "nss", "freetype", "harfbuzz"]

[phases.install]
cmds = ["cd server && npm ci"]

[phases.build]
cmds = ["cd server && npm run build || true"]

[start]
cmd = "cd server && npm start"

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/nix/var/nix/profiles/default/bin/chromium"
